title: 'أدوات | adawat'
email: your-email@example.com
description: >-
    A public catalouge for Arabic NLP tools
baseurl: '/adawat'
url: ''
twitter_username: jekyllrb
github_username: jekyll

plugins:
    - jekyll-feed

include: ['_pages']
